name: Update News

on:
  schedule:
    - cron: '0 */4 * * *' # Var 4:e timme
  workflow_dispatch: # Knapp för att köra manuellt

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout content
      uses: actions/checkout@v3
      with:
        ref: main # Tvingar den att använda main-branchen

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Generate News HTML
      run: python generator.py

    - name: Check if file exists
      run: |
        ls -l index.html

    - name: Commit and Push changes
      run: |
        git config --global user.name 'SpeculaBot'
        git config --global user.email 'bot@specula.ai'
        git add index.html
        # Spara endast om det finns ändringar
        git diff --staged --quiet || (git commit -m "Auto-update news [skip ci]" && git push origin main)
